# Generated by Django 4.2.1 on 2023-05-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='raiting',
            field=models.IntegerField(default=0),
        ),
    ]
