# Generated by Django 4.2.1 on 2023-05-30 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_remove_tag_books_book_tags'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('ru', 'Russian'), ('en', 'English'), ('fr', 'French')], default='ru', max_length=2)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='books.publisher'),
        ),
    ]
