# Generated by Django 4.2.1 on 2023-06-01 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_publisher_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Книга', 'verbose_name_plural': 'Книги'},
        ),
    ]
